# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
#在程序中如此引用：{{site.title}}   {{site.url}}
title: Minglei Yin
subTitle: I eat alone. I sleep alone. I cry alone. Sooooo...cool.
description: 这是 axhiao 的又一个博客，它是基于 Jekyll 搭建起来的。
url: http://axhiao.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 简历
    url: http://caleb.digitcv.com/#/resume
  - text: 联系我
    url: mailto:axhiao@gmail.com
  - text: 博客源代码
    url: https://github.com/axhiao/axhiao.github.io

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: https://plus.google.com/111646652304953916573/about
  - class: fa-facebook
    url: https://www.facebook.com/minglei.yin
  - class: fa-github
    url: http://github.com/axhiao
  - class: fa-weibo
    url: http://weibo.com/axhiao
#  - class: fa-renren
#    url: http://www.zhanxin.info
#  - class: fa-pinterest
#    url: http://www.zhanxin.info
  - class: fa-twitter
    url: http://www.twitter.com/Mr_YinMinglei
#  - class: fa-rss
#    url: http://www.zhanxin.info

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: axhiao

duoshuo:
  config: false
  id: zhanxin
